HOST: http://restaurants.tastebuds-app.com/

--- Tastebuds API ---

---
Welcome to the our sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
Favourites
The following is a section of resources related to the users' favourite restaurant
--

**Login Required.**
List restaurants added into your favourites list.
GET /api/favourites
< 200
< Content-Type: application/json
[
    {
        "restaurant_id": "43",
        "name": "Sample Restaurant",
        "url": "http://restaurants.tastebuds-app.com/restaurants/view/43",
        "created_on_display_text": "12 January 2013",
        "address": "",
        "postal_code": "",
        "website": "",
        "contact_number": "",
        "nearest_mrt": "",
        "reservation_policy": "",
        "created_by": "0",
        "created_on": "2013-01-12 09:03:17",
        "updated_on": "2013-01-12 09:05:45",
        "description": "",
        "picture": "43_e09f152aaf994168a411c9c0bd42cdc1.jpg",
        "picture_full_url": "43_e09f152aaf994168a411c9c0bd42cdc1.jpg",
        "_permissions": [
            "VIEW"
        ],
        "is_approved": "0",
        "opening_hours": [
            {
                "opening_hour_id": "49",
                "restaurant_id": "43",
                "day_start": "",
                "day_end": "",
                "time_start": "00:00",
                "time_end": "00:00",
                "created_on": "2013-01-12 09:03:20",
                "updated_on": "2013-01-12 09:03:20",
                "time_start_hour": "00",
                "time_start_minute": "00",
                "time_end_hour": "00",
                "time_end_minute": "00",
                "display_text": "-: 00:00-00:00"
            }
        ],
        "category": {},
        "cuisine": {},
        "location": [],
        "price_range": {},
        "statistics": {
            "restaurant_id": "43",
            "likes": "1",
            "recommendations": "1",
            "recommendations_female": "0",
            "recommendations_male": "0",
            "recommendations_last30days": "0",
            "recommendations_menu": "0",
            "updated_on": "2013-03-25 11:00:51",
            "restaurant_menus": []
        },
        "promotion": [],
        "comments": [],
        "recommendations_summary_display_text": "",
        "recommendations": [
            {
                "restaurants_recommendations_receivers": "36",
                "restaurant_recommendation_id": "26",
                "receiver_user_id": "0",
                "fb_uid": "684816214",
                "receiver_email": "",
                "has_read": "0",
                "updated_on": "2013-02-02 18:02:13",
                "sender_user_id": "3",
                "restaurant_id": "43",
                "restaurant_menu_ids": [],
                "remarks": "The food here is really good! ",
                "other_data": "",
                "sender_users": [
                    {
                        "id": "3",
                        "user_id": "3",
                        "username": "suyuen",
                        "email": "suyuen@gmail.com",
                        "first_name": "Su Yuen",
                        "last_name": "Chin",
                        "company": "MokoMomo Interactive",
                        "phone": "+65-97319993",
                        "created_on": "1352276324",
                        "display_name": "Su Yuen, Chin"
                    }
                ]
            }
        ],
        "user_session_rel_data": {
            "favourite": {
                "user_id": "1001",
                "fb_id": "0",
                "restaurant_id": "43",
                "updated_on": "2013-01-12 09:05:45",
                "name": "Sample Restaurant",
                "picture": "43_e09f152aaf994168a411c9c0bd42cdc1.jpg",
                "address": "",
                "postal_code": "",
                "website": "",
                "contact_number": "",
                "description": "",
                "price_range": "0",
                "category": "0",
                "cuisine": "0",
                "location": "0",
                "nearest_mrt": "",
                "reservation_policy": "",
                "created_by": "0",
                "created_on": "2013-01-12 09:03:17",
                "is_approved": "0",
                "is_saved": "0",
                "is_deleted": "0"
            }
        }
    }
]

**Login Required.**
Add a restaurant as favourite
POST /api/favourites
> Content-Type: application/json
{ "restaurant_id":"4722" }
< 201
< Content-Type: application/json
{
    "user_id": "1001",
    "fb_id": "0",
    "restaurant_id": "4722",
    "updated_on": "2013-02-27 14:44:47",
    "name": "Starbucks Coffee (Fullerton)",
    "picture": "http://tastebuds-media-s3-1.s3.amazonaws.com/restaurants/4722/header-coffee_house.jpg",
    "address": "1 Fullerton Road",
    "postal_code": "S049213",
    "website": "http://www.starbucks.com",
    "contact_number": "63279245",
    "description": "Starbucks Corporation is an American global coffee company and coffeehouse chain based in Seattle, Washington. Starbucks is the largest coffeehouse company in the world, with 20,366 stores in 61 countries, including 13,123 in the United States, 1,299 in Canada, 977 in Japan, 793 in the United Kingdom, 732 in China, 473 in South Korea, 363 in Mexico, 282 in Taiwan, 204 in the Philippines, and 164 in Thailand.",
    "price_range": "1",
    "category": "0",
    "cuisine": "30",
    "location": "71",
    "nearest_mrt": "",
    "reservation_policy": "Starbucks Coffee Singapore Private Ltd (\"Starbucks\" or \"we\" or \"us\")\nStarbucks Card Account Terms of Use and Agreement",
    "created_by": "1001",
    "created_on": "2013-01-19 06:25:13",
    "is_approved": "1",
    "is_saved": "1",
    "is_deleted": "0"
}

**Login Required.**
Remove a restaurant as favourite
DELETE /api/favourites
> Content-Type: application/json
{ "restaurant_id":"4722" }
< 201
< Content-Type: application/json
true


-- 
Restaurant 
The following is a section of resources related to CRUD of restaurant object.
--

This resource allows you to get a restaurant
GET /api/restaurant/
{ "restaurant_id": "43" }
< 200
{
    "restaurant_id": "43",
    "name": "Sample Restaurant",
    "url": "http://restaurants.tastebuds-app.com/restaurants/view/43",
    "created_on_display_text": "12 January 2013",
    "address": "",
    "postal_code": "",
    "website": "",
    "contact_number": "",
    "nearest_mrt": "",
    "reservation_policy": "",
    "created_by": "0",
    "created_on": "2013-01-12 09:03:17",
    "updated_on": "2013-01-12 09:05:45",
    "description": "",
    "picture": "43_e09f152aaf994168a411c9c0bd42cdc1.jpg",
    "picture_full_url": "43_e09f152aaf994168a411c9c0bd42cdc1.jpg",
    "_permissions": [
        "VIEW"
    ],
    "is_approved": "0",
    "opening_hours": [
        {
            "opening_hour_id": "49",
            "restaurant_id": "43",
            "day_start": "",
            "day_end": "",
            "time_start": "00:00",
            "time_end": "00:00",
            "created_on": "2013-01-12 09:03:20",
            "updated_on": "2013-01-12 09:03:20",
            "time_start_hour": "00",
            "time_start_minute": "00",
            "time_end_hour": "00",
            "time_end_minute": "00",
            "display_text": "-: 00:00-00:00"
        }
    ],
    "category": {},
    "cuisine": {},
    "location": [],
    "price_range": {},
    "statistics": {
        "restaurant_id": "43",
        "likes": "1",
        "recommendations": "1",
        "recommendations_female": "0",
        "recommendations_male": "0",
        "recommendations_last30days": "0",
        "recommendations_menu": "0",
        "updated_on": "2013-03-25 11:00:51",
        "restaurant_menus": []
    },
    "promotion": [],
    "comments": [],
    "recommendations_summary_display_text": "",
    "recommendations": [
        {
            "restaurants_recommendations_receivers": "36",
            "restaurant_recommendation_id": "26",
            "receiver_user_id": "0",
            "fb_uid": "684816214",
            "receiver_email": "",
            "has_read": "0",
            "updated_on": "2013-02-02 18:02:13",
            "sender_user_id": "3",
            "restaurant_id": "43",
            "restaurant_menu_ids": [],
            "remarks": "The food here is really good! ",
            "other_data": "",
            "sender_users": [
                {
                    "id": "3",
                    "user_id": "3",
                    "username": "suyuen",
                    "email": "suyuen@gmail.com",
                    "first_name": "Su Yuen",
                    "last_name": "Chin",
                    "company": "MokoMomo Interactive",
                    "phone": "+65-97319993",
                    "created_on": "1352276324",
                    "display_name": "Su Yuen, Chin"
                }
            ]
        }
    ],
    "user_session_rel_data": {
        "favourite": {
            "user_id": "1001",
            "fb_id": "0",
            "restaurant_id": "43",
            "updated_on": "2013-01-12 09:05:45",
            "name": "Sample Restaurant",
            "picture": "43_e09f152aaf994168a411c9c0bd42cdc1.jpg",
            "address": "",
            "postal_code": "",
            "website": "",
            "contact_number": "",
            "description": "",
            "price_range": "0",
            "category": "0",
            "cuisine": "0",
            "location": "0",
            "nearest_mrt": "",
            "reservation_policy": "",
            "created_by": "0",
            "created_on": "2013-01-12 09:03:17",
            "is_approved": "0",
            "is_saved": "0",
            "is_deleted": "0"
        }
    }
}

This resource allows you to update a restaurant
POST /api/restaurant/
{ "restaurant_id": "4722" }
< 200
{
    "restaurant_id": "4722",
    "name": "Starbucks Coffee (Fullerton)",
    "url": "http://restaurants.tastebuds-app.com/restaurants/view/4722",
    "created_on_display_text": "19 January 2013",
    "address": "1 Fullerton Road",
    "postal_code": "S049213",
    "website": "http://www.starbucks.com",
    "contact_number": "63279245",
    "nearest_mrt": "Raffles Place",
    "reservation_policy": "Starbucks Coffee Singapore Private Ltd (\"Starbucks\" or \"we\" or \"us\")\nStarbucks Card Account Terms of Use and Agreement",
    "created_by": "1001",
    "created_on": "2013-01-19 06:25:13",
    "updated_on": "2013-02-27 14:44:47",
    "description": "Starbucks Corporation is an American global coffee company and coffeehouse chain based in Seattle, Washington. Starbucks is the largest coffeehouse company in the world, with 20,366 stores in 61 countries, including 13,123 in the United States, 1,299 in Canada, 977 in Japan, 793 in the United Kingdom, 732 in China, 473 in South Korea, 363 in Mexico, 282 in Taiwan, 204 in the Philippines, and 164 in Thailand.",
    "picture": "http://tastebuds-media-s3-1.s3.amazonaws.com/restaurants/4722/header-coffee_house.jpg",
    "picture_full_url": "http://tastebuds-media-s3-1.s3.amazonaws.com/restaurants/4722/header-coffee_house.jpg",
    "_permissions": [
        "VIEW",
        "UPDATE",
        "DELETE"
    ],
    "is_approved": "1",
    "opening_hours": [
        {
            "opening_hour_id": "122",
            "restaurant_id": "4722",
            "day_start": "Mon",
            "day_end": "Fri",
            "time_start": "08:00",
            "time_end": "22:00",
            "created_on": "2013-01-19 06:25:15",
            "updated_on": "2013-02-27 14:42:52",
            "time_start_hour": "08",
            "time_start_minute": "00",
            "time_end_hour": "22",
            "time_end_minute": "00",
            "display_text": "Mon-Fri: 08:00-22:00"
        },
        {
            "opening_hour_id": "159",
            "restaurant_id": "4722",
            "day_start": "Sat",
            "day_end": "Sun",
            "time_start": "08:00",
            "time_end": "23:45",
            "created_on": "2013-02-27 14:42:41",
            "updated_on": "2013-02-27 14:43:07",
            "time_start_hour": "08",
            "time_start_minute": "00",
            "time_end_hour": "23",
            "time_end_minute": "45",
            "display_text": "Sat-Sun: 08:00-23:45"
        }
    ],
    "category": {},
    "cuisine": {
        "cuisine_id": "30",
        "cuisine_name": "Western - Other",
        "created_on": "2013-01-15 20:46:55",
        "updated_on": "2013-01-15 20:47:08"
    },
    "location": {
        "location_id": "71",
        "location_name": "Raffles Place",
        "created_on": "2013-01-15 20:57:59",
        "updated_on": "2013-01-15 20:58:05"
    },
    "price_range": {
        "price_group_id": "1",
        "price_range_lower": "0.00",
        "price_range_upper": "15.00",
        "created_on": "2012-10-18 23:22:47",
        "updated_on": "2012-12-25 18:35:55",
        "display_text": "< $15"
    },
    "statistics": {
        "restaurant_id": "4722",
        "likes": "1",
        "recommendations": "60",
        "recommendations_female": "0",
        "recommendations_male": "0",
        "recommendations_last30days": "36",
        "recommendations_menu": "59",
        "updated_on": "2013-03-25 00:49:56",
        "restaurant_menus": [
            {
                "restaurant_menu_id": "66",
                "restaurant_id": "4722",
                "menu_name": "Espresso",
                "menu_picture": "http://tastebuds-media-s3-1.s3.amazonaws.com/restaurants_menu/66/espresso_espresso_z.jpg",
                "menu_price": "10.00",
                "menu_category_id": "39",
                "menu_description": "Smooth and versatile Espresso Roast is the very heart and soul of Starbucks. Its rich flavor, lingering aroma and caramelly sweetness make it the perfect foundation for lattes, cappuccinos and all our espresso-based beverages. But you can also enjoy it all by itself – indeed, that might be the best way to discover its nuances.",
                "created_on": "2013-01-22 14:25:44",
                "updated_on": "2013-01-22 14:26:28",
                "menu_picture_full_url": "http://tastebuds-media-s3-1.s3.amazonaws.com/restaurants_menu/66/espresso_espresso_z.jpg",
                "statistics": {
                    "count_recommendations_last30": 38
                }
            },
            {
                "restaurant_menu_id": "67",
                "restaurant_id": "4722",
                "menu_name": "Caffè Americano",
                "menu_picture": "http://tastebuds-media-s3-1.s3.amazonaws.com/restaurants_menu/67/espresso_caffe_americano_z.jpg",
                "menu_price": "11.00",
                "menu_category_id": "39",
                "menu_description": "In Europe, coffee is essentially espresso – which, in America, isn’t very much coffee. To create a caffè americano – a coffee that satisfies the American preference for more sips in every cup – Europeans simply add hot water to their espresso. While the americano is similar in strength and taste to American-style brewed coffee, there are subtle differences achieved by pulling a fresh shot of espresso for the beverage base. The best way to discover these nuances, of course, is to try a cup yourself.",
                "created_on": "2013-01-22 14:26:42",
                "updated_on": "2013-01-22 14:27:07",
                "menu_picture_full_url": "http://tastebuds-media-s3-1.s3.amazonaws.com/restaurants_menu/67/espresso_caffe_americano_z.jpg",
                "statistics": {
                    "count_recommendations_last30": 3
                }
            }
        ]
    },
    "admins": [
        {
            "restaurant_admins_id": "90",
            "restaurant_id": "4722",
            "user_id": "1001",
            "first_name": "",
            "last_name": "",
            "email": "",
            "contact_number": "",
            "udpated_on": "2013-01-19 06:25:15"
        }
    ],
    "promotion": [
        {
            "restaurant_promotion_id": "14",
            "restaurant_id": "4722",
            "promotion_name": "Happy Hour: 10% off all coffee",
            "promotion_description": "Testing only.",
            "promotion_fine_print": "",
            "start_date": "2013-01-01",
            "end_date": "2013-03-31",
            "expiry_date": "0000-00-00",
            "created_on": "2013-01-20",
            "updated_on": "2013-03-19 15:21:34",
            "start_date_display_text": "01 January 2013",
            "end_date_display_text": "31 March 2013"
        },
        {
            "restaurant_promotion_id": "15",
            "restaurant_id": "4722",
            "promotion_name": "Awesome Curry Chicken Free!",
            "promotion_description": "This is the description this is the description  this is the description  this is the description  this is the description ",
            "promotion_fine_print": "",
            "start_date": "2013-01-28",
            "end_date": "2013-03-31",
            "expiry_date": "0000-00-00",
            "created_on": "2013-02-01",
            "updated_on": "2013-03-19 15:21:40",
            "start_date_display_text": "28 January 2013",
            "end_date_display_text": "31 March 2013"
        }
    ],
    "comments": [],
    "recommendations_summary_display_text": "",
    "recommendations": [
        {
            "restaurants_recommendations_receivers": "1",
            "restaurant_recommendation_id": "1",
            "receiver_user_id": "0",
            "fb_uid": "684816214",
            "receiver_email": "",
            "has_read": "0",
            "updated_on": "2013-01-19 15:56:15",
            "sender_user_id": "1001",
            "restaurant_id": "4722",
            "restaurant_menu_ids": [
                "66",
                "67"
            ],
            "remarks": "Testing.",
            "other_data": "",
            "sender_users": [
                {
                    "id": "1",
                    "user_id": "1",
                    "username": "administrator",
                    "email": "admin@admin.com",
                    "first_name": "Admin",
                    "last_name": "istrator",
                    "company": "ADMIN",
                    "phone": "0",
                    "created_on": "1268889823",
                    "display_name": "Admin, istrator"
                },
                {
                    "id": "3",
                    "user_id": "3",
                    "username": "suyuen",
                    "email": "suyuen@gmail.com",
                    "first_name": "Su Yuen",
                    "last_name": "Chin",
                    "company": "MokoMomo Interactive",
                    "phone": "+65-97319993",
                    "created_on": "1352276324",
                    "display_name": "Su Yuen, Chin"
                },
                {
                    "id": "1",
                    "user_id": "1",
                    "username": "administrator",
                    "email": "admin@admin.com",
                    "first_name": "Admin",
                    "last_name": "istrator",
                    "company": "ADMIN",
                    "phone": "0",
                    "created_on": "1268889823",
                    "display_name": "Admin, istrator"
                }
            ],
            "recommended_menus": [
                {
                    "restaurant_menu_id": "66",
                    "restaurant_id": "4722",
                    "menu_name": "Espresso",
                    "menu_picture": "http://tastebuds-media-s3-1.s3.amazonaws.com/restaurants_menu/66/espresso_espresso_z.jpg",
                    "menu_price": "10.00",
                    "menu_category_id": "39",
                    "menu_description": "Smooth and versatile Espresso Roast is the very heart and soul of Starbucks. Its rich flavor, lingering aroma and caramelly sweetness make it the perfect foundation for lattes, cappuccinos and all our espresso-based beverages. But you can also enjoy it all by itself – indeed, that might be the best way to discover its nuances.",
                    "created_on": "2013-01-22 14:25:44",
                    "updated_on": "2013-01-22 14:26:28",
                    "menu_picture_full_url": "http://tastebuds-media-s3-1.s3.amazonaws.com/restaurants_menu/66/espresso_espresso_z.jpg",
                    "category": {
                        "menu_category_id": "39",
                        "restaurant_id": "4722",
                        "user_id": "1001",
                        "menu_category_name": "Espresso and Coffee Classics",
                        "created_on": "2013-01-19 14:10:06",
                        "updated_on": "2013-01-22 14:23:15"
                    },
                    "uploaded_images": [
                        {
                            "restaurants_recommendations_menu_images_id": "4",
                            "restaurant_recommendation_id": "12",
                            "restaurant_menu_id": "66",
                            "picture": "http://tastebuds-media-s3-1.s3.amazonaws.com/recommendations/12/66/6.7_.Dish_.jpg",
                            "restaurant_menu_comment": "",
                            "updated_on": "2013-01-28 16:55:04",
                            "picture_full_url": "http://tastebuds-media-s3-1.s3.amazonaws.com/recommendations/12/66/6.7_.Dish_.jpg"
                        },
                        {
                            "restaurants_recommendations_menu_images_id": "5",
                            "restaurant_recommendation_id": "13",
                            "restaurant_menu_id": "66",
                            "picture": "http://tastebuds-media-s3-1.s3.amazonaws.com/recommendations/13/66/10823000.jpeg",
                            "restaurant_menu_comment": "",
                            "updated_on": "2013-01-28 16:56:57",
                            "picture_full_url": "http://tastebuds-media-s3-1.s3.amazonaws.com/recommendations/13/66/10823000.jpeg"
                        },
                        {
                            "restaurants_recommendations_menu_images_id": "6",
                            "restaurant_recommendation_id": "14",
                            "restaurant_menu_id": "66",
                            "picture": "http://tastebuds-media-s3-1.s3.amazonaws.com/recommendations/14/66/10589e80.jpeg",
                            "restaurant_menu_comment": "",
                            "updated_on": "2013-01-28 17:01:07",
                            "picture_full_url": "http://tastebuds-media-s3-1.s3.amazonaws.com/recommendations/14/66/10589e80.jpeg"
                        },
                        {
                            "restaurants_recommendations_menu_images_id": "7",
                            "restaurant_recommendation_id": "21",
                            "restaurant_menu_id": "66",
                            "picture": "http://tastebuds-media-s3-1.s3.amazonaws.com/recommendations/21/66/1075c400.jpeg",
                            "restaurant_menu_comment": "",
                            "updated_on": "2013-02-02 17:01:45",
                            "picture_full_url": "http://tastebuds-media-s3-1.s3.amazonaws.com/recommendations/21/66/1075c400.jpeg"
                        },
                        {
                            "restaurants_recommendations_menu_images_id": "8",
                            "restaurant_recommendation_id": "22",
                            "restaurant_menu_id": "66",
                            "picture": "http://tastebuds-media-s3-1.s3.amazonaws.com/recommendations/22/66/f3b0020.jpeg",
                            "restaurant_menu_comment": "",
                            "updated_on": "2013-02-02 17:07:21",
                            "picture_full_url": "http://tastebuds-media-s3-1.s3.amazonaws.com/recommendations/22/66/f3b0020.jpeg"
                        },
                        {
                            "restaurants_recommendations_menu_images_id": "9",
                            "restaurant_recommendation_id": "23",
                            "restaurant_menu_id": "66",
                            "picture": "http://tastebuds-media-s3-1.s3.amazonaws.com/recommendations/23/66/1085b160.jpeg",
                            "restaurant_menu_comment": "",
                            "updated_on": "2013-02-02 17:08:33",
                            "picture_full_url": "http://tastebuds-media-s3-1.s3.amazonaws.com/recommendations/23/66/1085b160.jpeg"
                        },
                        {
                            "restaurants_recommendations_menu_images_id": "10",
                            "restaurant_recommendation_id": "61",
                            "restaurant_menu_id": "66",
                            "picture": "http://tastebuds-media-s3-1.s3.amazonaws.com/recommendations/61/66/b35a170.jpeg",
                            "restaurant_menu_comment": "",
                            "updated_on": "2013-03-22 15:00:25",
                            "picture_full_url": "http://tastebuds-media-s3-1.s3.amazonaws.com/recommendations/61/66/b35a170.jpeg"
                        }
                    ]
                },
                {
                    "restaurant_menu_id": "67",
                    "restaurant_id": "4722",
                    "menu_name": "Caffè Americano",
                    "menu_picture": "http://tastebuds-media-s3-1.s3.amazonaws.com/restaurants_menu/67/espresso_caffe_americano_z.jpg",
                    "menu_price": "11.00",
                    "menu_category_id": "39",
                    "menu_description": "In Europe, coffee is essentially espresso – which, in America, isn’t very much coffee. To create a caffè americano – a coffee that satisfies the American preference for more sips in every cup – Europeans simply add hot water to their espresso. While the americano is similar in strength and taste to American-style brewed coffee, there are subtle differences achieved by pulling a fresh shot of espresso for the beverage base. The best way to discover these nuances, of course, is to try a cup yourself.",
                    "created_on": "2013-01-22 14:26:42",
                    "updated_on": "2013-01-22 14:27:07",
                    "menu_picture_full_url": "http://tastebuds-media-s3-1.s3.amazonaws.com/restaurants_menu/67/espresso_caffe_americano_z.jpg",
                    "category": {
                        "menu_category_id": "39",
                        "restaurant_id": "4722",
                        "user_id": "1001",
                        "menu_category_name": "Espresso and Coffee Classics",
                        "created_on": "2013-01-19 14:10:06",
                        "updated_on": "2013-01-22 14:23:15"
                    },
                    "uploaded_images": [
                        {
                            "restaurants_recommendations_menu_images_id": "11",
                            "restaurant_recommendation_id": "63",
                            "restaurant_menu_id": "67",
                            "picture": "http://tastebuds-media-s3-1.s3.amazonaws.com/recommendations/63/67/d67a0d0.jpeg",
                            "restaurant_menu_comment": "",
                            "updated_on": "2013-03-23 04:28:57",
                            "picture_full_url": "http://tastebuds-media-s3-1.s3.amazonaws.com/recommendations/63/67/d67a0d0.jpeg"
                        }
                    ]
                }
            ]
        }
    ],
    "user_session_rel_data": {
        "favourite": {
            "user_id": "1001",
            "fb_id": "0",
            "restaurant_id": "4722",
            "updated_on": "2013-02-27 14:44:47",
            "name": "Starbucks Coffee (Fullerton)",
            "picture": "http://tastebuds-media-s3-1.s3.amazonaws.com/restaurants/4722/header-coffee_house.jpg",
            "address": "1 Fullerton Road",
            "postal_code": "S049213",
            "website": "http://www.starbucks.com",
            "contact_number": "63279245",
            "description": "Starbucks Corporation is an American global coffee company and coffeehouse chain based in Seattle, Washington. Starbucks is the largest coffeehouse company in the world, with 20,366 stores in 61 countries, including 13,123 in the United States, 1,299 in Canada, 977 in Japan, 793 in the United Kingdom, 732 in China, 473 in South Korea, 363 in Mexico, 282 in Taiwan, 204 in the Philippines, and 164 in Thailand.",
            "price_range": "1",
            "category": "0",
            "cuisine": "30",
            "location": "71",
            "nearest_mrt": "",
            "reservation_policy": "Starbucks Coffee Singapore Private Ltd (\"Starbucks\" or \"we\" or \"us\")\nStarbucks Card Account Terms of Use and Agreement",
            "created_by": "1001",
            "created_on": "2013-01-19 06:25:13",
            "is_approved": "1",
            "is_saved": "1",
            "is_deleted": "0"
        }
    }
}


-- 
Search 
The following is a section of resources related to the search tool.
--

This resource allows you to search for restaurants
GET /api/search/
{ "keywords": "starbucks", "page": "1" }
< 200
[
    {
        "restaurant_id": "4722",
        "name": "Starbucks Coffee (Fullerton)",
        "url": "http://restaurants.tastebuds-app.com/restaurants/view/4722",
        "created_on_display_text": "19 January 2013",
        "address": "1 Fullerton Road",
        "postal_code": "S049213",
        "website": "http://www.starbucks.com",
        "contact_number": "63279245",
        "nearest_mrt": "Raffles Place",
        "reservation_policy": "Starbucks Coffee Singapore Private Ltd (\"Starbucks\" or \"we\" or \"us\")\nStarbucks Card Account Terms of Use and Agreement",
        "created_by": "1001",
        "created_on": "2013-01-19 06:25:13",
        "updated_on": "2013-02-27 14:44:47",
        "description": "Starbucks Corporation is an American global coffee company and coffeehouse chain based in Seattle, Washington. Starbucks is the largest coffeehouse company in the world, with 20,366 stores in 61 countries, including 13,123 in the United States, 1,299 in Canada, 977 in Japan, 793 in the United Kingdom, 732 in China, 473 in South Korea, 363 in Mexico, 282 in Taiwan, 204 in the Philippines, and 164 in Thailand.",
        "picture": "http://tastebuds-media-s3-1.s3.amazonaws.com/restaurants/4722/header-coffee_house.jpg",
        "picture_full_url": "http://tastebuds-media-s3-1.s3.amazonaws.com/restaurants/4722/header-coffee_house.jpg",
        "_permissions": [
            "VIEW",
            "UPDATE",
            "DELETE"
        ],
        "is_approved": "1",
        "opening_hours": [
            {
                "opening_hour_id": "122",
                "restaurant_id": "4722",
                "day_start": "Mon",
                "day_end": "Fri",
                "time_start": "08:00",
                "time_end": "22:00",
                "created_on": "2013-01-19 06:25:15",
                "updated_on": "2013-02-27 14:42:52",
                "time_start_hour": "08",
                "time_start_minute": "00",
                "time_end_hour": "22",
                "time_end_minute": "00",
                "display_text": "Mon-Fri: 08:00-22:00"
            },
            {
                "opening_hour_id": "159",
                "restaurant_id": "4722",
                "day_start": "Sat",
                "day_end": "Sun",
                "time_start": "08:00",
                "time_end": "23:45",
                "created_on": "2013-02-27 14:42:41",
                "updated_on": "2013-02-27 14:43:07",
                "time_start_hour": "08",
                "time_start_minute": "00",
                "time_end_hour": "23",
                "time_end_minute": "45",
                "display_text": "Sat-Sun: 08:00-23:45"
            }
        ],
        "category": {},
        "cuisine": {
            "cuisine_id": "30",
            "cuisine_name": "Western - Other",
            "created_on": "2013-01-15 20:46:55",
            "updated_on": "2013-01-15 20:47:08"
        },
        "location": {
            "location_id": "71",
            "location_name": "Raffles Place",
            "created_on": "2013-01-15 20:57:59",
            "updated_on": "2013-01-15 20:58:05"
        },
        "price_range": {
            "price_group_id": "1",
            "price_range_lower": "0.00",
            "price_range_upper": "15.00",
            "created_on": "2012-10-18 23:22:47",
            "updated_on": "2012-12-25 18:35:55",
            "display_text": "< $15"
        },
        "admins": [
            {
                "restaurant_admins_id": "90",
                "restaurant_id": "4722",
                "user_id": "1001",
                "first_name": "",
                "last_name": "",
                "email": "",
                "contact_number": "",
                "udpated_on": "2013-01-19 06:25:15"
            }
        ],
        "user_session_rel_data": {
            "favourite": []
        }
    }
]


